=== dmzoneill/www.feeditout.com-2008/samples/yang/movie.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT dvd (title,picture,director+,actors+,production,producers,plot,copyright,released)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT picture (#PCDATA)>
<!ELEMENT director (firstname?,surname)>
<!ELEMENT actors (firstname?,surname)>
<!ELEMENT production (#PCDATA)>
<!ELEMENT producers (firstname?,surname)>
<!ELEMENT plot (#PCDATA)>
<!ELEMENT copyright (#PCDATA)>
<!ELEMENT released (#PCDATA)>

<!ELEMENT firstname (#PCDATA)>
<!ELEMENT surname (#PCDATA)>

<!ATTLIST dvd 
    genre CDATA #IMPLIED
    runtime CDATA #REQUIRED  
    viewing (PG | 12 | 15 | 18) #REQUIRED
    language CDATA #IMPLIED
    imdb CDATA #IMPLIED
>
<!ATTLIST director 
    nationality CDATA #IMPLIED
    sex CDATA "male|female"  
>
<!ATTLIST actors 
    nationality CDATA #IMPLIED
    sex CDATA "male|female"  
>

=== dmzoneill/www.feeditout.com-2008/samples/yang/m1.xml
<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE dvd SYSTEM "movie.dtd">
<dvd runtime="99" viewing="12" language="jp" genre="drama" imdb="http://www.imdb.com/title/tt1190080/">
    <title>2012</title>
    <picture>2012.jpg</picture>
    <director>
        <firstname>Roland </firstname>
        <surname>Emmerich</surname>
    </director>
    <actors>
        <firstname>John</firstname>
        <surname>Cusack</surname>
    </actors>
    <actors>
        <firstname>Amanda</firstname>
        <surname>Peet</surname>
    </actors>
    <actors>
        <firstname>Chiwetel</firstname>
        <surname>Ejiofor</surname>
    </actors>
    <production>Dreame Works</production>
    <producers>
        <firstname>Johann</firstname>
        <surname>Urb</surname>
    </producers>
    <plot>An epic adventure about a global cataclysm that brings an end to the world and tells of the heroic struggle of the survivors.</plot>
    <copyright>Harald Klose</copyright>
    <released>2009</released>
</dvd>

=== dmzoneill/www.feeditout.com-2008/samples/yang/m2.xml
<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE dvd SYSTEM "movie.dtd">
<dvd runtime="132" viewing="18" genre="horor" imdb="http://www.imdb.com/title/tt1099212/" language="en">
    <title>Twilight</title>
    <picture>twilight.jpg</picture>
    <director>
        <firstname>Catherine</firstname>
        <surname>Hardwicke</surname>
    </director>
    <actors>
        <firstname>Kristen</firstname>
        <surname>Stewart</surname>
    </actors>
    <actors>
        <firstname>Sarah</firstname>
        <surname>Clarke</surname>
    </actors>
    <actors>
        <firstname>Robert</firstname>
        <surname>Pattinson</surname>
    </actors>
    <actors>
        <firstname>Matt</firstname>
        <surname>Bushell</surname>
    </actors>
    <production>Pixar</production>
    <producers>
        <firstname>Kellan </firstname>
        <surname>Lutz</surname>
    </producers>
    <plot>A teenage girl risks everything when she falls in love with a vampire.</plot>
    <copyright>Stephenie Meyer</copyright>
    <released>2008</released>
</dvd>

=== dmzoneill/www.feeditout.com-2008/samples/yang/m3.xml
<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE dvd SYSTEM "movie.dtd">
<dvd runtime="154" viewing="15" imdb="http://www.imdb.com/title/tt0230600/" language="ch">
    <title>The Others</title>
    <picture>theOthers.jpg</picture>
    <director>
        <firstname>Alejandro</firstname>
        <surname>Amenábar</surname>
    </director>
    <actors>
        <firstname>Nicole</firstname>
        <surname>Kidman</surname>
    </actors>
    <actors>
        <firstname>Fionnula</firstname>
        <surname>Flanagan</surname>
    </actors>
    <actors>
        <firstname>Christopher</firstname>
        <surname>Eccleston</surname>
    </actors>
    <production>Sony entertament</production>
    <producers>
        <firstname>Keith</firstname>
        <surname>Allen</surname>
    </producers>
    <plot>A woman who lives in a darkened old house with her two photosensitive children becomes convinced that her family home is haunted.</plot>
    <copyright>Alejandro Amenábar</copyright>
    <released>2001</released>
</dvd>
