=== dmzoneill/www.feeditout.com-2008/samples/project2/dvd.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT dvd
(
    title, 
    presenter, 
    production, 
    released, 
    producers,
    coProducers,
    musicProducers, 
    costumeDesigners,
    directors,
    actors,
    plot,
    copyright,
    other
)>
<!-- begin description of book and child elements -->
<!ATTLIST dvd genre CDATA #REQUIRED>
<!ATTLIST dvd runtime CDATA #REQUIRED>
<!ATTLIST dvd lang CDATA "en">
<!ATTLIST dvd viewing ( PG | 12 | 15 | 18 ) #REQUIRED>

<!ELEMENT title ( #PCDATA )>
<!ELEMENT presenter (companyname)+>
<!ELEMENT production (companyname)+>
<!ELEMENT released (date)>
<!ELEMENT producers (person)+>
<!ELEMENT coProducers (person)+>
<!ELEMENT musicProducers (person)+>
<!ELEMENT costumeDesigners (person)+>
<!ELEMENT directors (person)+>

<!ELEMENT actors (person)+>
<!ELEMENT plot (#PCDATA) >

<!ELEMENT copyright ( date*, ( companyname | person )* )>
<!ELEMENT date ( day?, month?, year )>
<!ELEMENT day ( #PCDATA )>
<!ELEMENT month ( #PCDATA )>
<!ELEMENT year ( #PCDATA )>

<!ELEMENT companyname ( #PCDATA )>
<!ATTLIST companyname lang CDATA "en">
<!ELEMENT person ( firstname, initial?, surname )>
<!ATTLIST person lang CDATA "en">
<!ATTLIST person sex CDATA #IMPLIED>
<!ELEMENT firstname ( #PCDATA )>
<!ELEMENT initial ( #PCDATA )>
<!ELEMENT surname ( #PCDATA )>

<!ELEMENT other ( imdblink*, picture?, price? )>
<!ELEMENT imdblink ( #PCDATA )>
<!ELEMENT picture ( #PCDATA )>
<!ELEMENT price ( #PCDATA )>

=== dmzoneill/www.feeditout.com-2008/samples/project2/dvd2.xml
<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE dvd SYSTEM "dvd.dtd">
<?xml-stylesheet href="reset.css" type="text/css"?>
<?xml-stylesheet href="dvd.css" type="text/css"?>
<dvd genre="comedy" runtime="113" viewing="18">    
    <title>Superbad</title>    
    <presenter>
        <companyname>Columbia Pictures</companyname>
    </presenter>
    <production>
        <companyname>Apatow Company</companyname>
    </production>
    <released>
        <date>
            <year>2007</year>
        </date>
    </released>
    <producers>
        <person>
            <firstname>Jonah</firstname>
            <surname>Hill</surname>
        </person>
        <person>
            <firstname>Michael</firstname>
            <surname>Cera</surname>
        </person>
        <person>
            <firstname>Seth</firstname>
            <surname>Rogen</surname>
        </person>
        <person>
            <firstname>Bill Hader</firstname>
            <surname>Rogen</surname>
        </person>
    </producers>
    <coProducers>
        <person>
            <firstname>Dara</firstname>
            <surname>Weintrab</surname>
        </person>
    </coProducers>
    <musicProducers>
        <person>
            <firstname>Lyle</firstname>
            <surname>Workman</surname>
        </person>
    </musicProducers>
    <costumeDesigners>
        <person>
            <firstname>Debra</firstname>
            <surname>McGuire</surname>
        </person>
    </costumeDesigners>
    <directors>
        <person>
            <firstname>Greg</firstname>
            <surname>Motolla</surname>
        </person>
    </directors>
    <actors>
        <person>
            <firstname>Jonah</firstname>
            <surname>Hill</surname>
        </person>
        <person>
            <firstname>Michael</firstname>
            <surname>Cera</surname>
        </person>
        <person>
            <firstname>Christopher</firstname>
            <surname>Mintz-Plasse</surname>
        </person>
        <person>
            <firstname>Bill</firstname>
            <surname>Hader</surname>
        </person>       
    </actors>
    <plot>
        Seth and Evan are best friends, inseparable, navigating the last weeks of high school. 
        Usually shunned by the popular kids, Seth and Evan luck into an invitation to a party, 
        and spend a long day, with the help of their nerdy friend Fogell, trying to score enough alcohol
        to lubricate the party and inebriate two girls, Jules and Becca, so they can kick-start their 
        sex lives and go off to college with a summer full of experience and new skills. 
        Their quest is complicated by Fogell's falling in with two inept cops who both slow and assist the plan.
        If they do get the liquor to the party, what then? Is sex the only rite of passage at hand? Written by {jhailey@hotmail.com}
        
        Seth, Evan and Fogell are three teenage guys who love to drink and desperately wish to get laid. 
        When a girl that Seth really likes, asks him to get the drink for her party, 
        he sees this as a perfect opportunity to make her his girlfriend. 
        The trio plan out how to get the alcohol, even including Fogell's new fake ID, but things won't
        got smoothly for the trio. Seth and Evan become separated from Fogell (now called McLovin) and
        they still haven't got the alcohol for the party that night.
    </plot>    
    <copyright>
        <date>
            <year>2007</year>
        </date>        
        <companyname>Sony Pictures</companyname>
    </copyright>
    <other>
        <imdblink>http://www.imdb.com/title/tt0829482/</imdblink>
        <picture>dvd2.png</picture>
        <price></price>
    </other>
</dvd>

=== dmzoneill/www.feeditout.com-2008/samples/project2/dvd1.xml
<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE dvd SYSTEM "dvd.dtd">
<?xml-stylesheet href="reset.css" type="text/css"?>
<?xml-stylesheet href="dvd.css" type="text/css"?>
<dvd genre="comedy" runtime="168" viewing="12">    
    <title>Employee of the month</title>    
    <presenter>
        <companyname>Lionsgate</companyname>
    </presenter>
    <production>
        <companyname>Tapestry Films</companyname>
    </production>
    <released>
        <date>
            <year>2006</year>
        </date>
    </released>
    <producers>
        <person>
            <firstname>Joe</firstname>
            <surname>Simpson</surname>
        </person>
        <person>
            <firstname>Barry</firstname>
            <surname>Katz</surname>
        </person>
        <person>
            <firstname>Brian</firstname>
            <surname>Volk-Weiss</surname>
        </person>       
    </producers>
    <coProducers>
        <person>
            <firstname>Andrew</firstname>
            <surname>Paney</surname>
        </person>
        <person>
            <firstname>Rebeccas</firstname>
            <surname>Mangeiri</surname>
        </person>        
    </coProducers>
    <musicProducers>
        <person>
            <firstname>John</firstname>
            <surname>Shwartz</surname>
        </person>
    </musicProducers>
    <costumeDesigners>
        <person>
            <firstname>Norah</firstname>
            <surname>Power</surname>
        </person>
    </costumeDesigners>
    <directors>
        <person>
            <firstname>Anette</firstname>
            <surname>Sweeney</surname>
        </person>
    </directors>
    <actors>
        <person>
            <firstname>Dane</firstname>
            <surname>Cook</surname>
        </person>
        <person>
            <firstname>Jessica</firstname>
            <surname>Simpson</surname>
        </person>
        <person>
            <firstname>Dax</firstname>
            <surname>Shepard</surname>
        </person>
        <person>
            <firstname>Andy</firstname>
            <surname>Dick</surname>
        </person>       
        <person>
            <firstname>Tim</firstname>
            <surname>Bagley</surname>
        </person>        
    </actors>
    <plot>
        At Super Club, a large warehouse store, the employees strive to obtain the &quot;Employee of the Month&quot;
        award with the benefits of having their picture featured on the wall of fame in the staff lounge. 
        Zack Bradley, a box boy, and Vince Downey, a cashier, are two competitive Super Club employees. 
        Vince has become head cashier of the store and winner of seventeen consecutive &quot;Employee of the Month&quot; awards. 
        Zack, on the other hand, is a slacker but is popular with his colleagues. &#10;&#10;         
        
        Zack has not won any &quot;Employee of the Month&quot; awards and has no desire to except when Amy, 
        a new cashier who only dates &quot;Employee of the Month&quot; winners, transfers to the store. 
        Zack and Vince compete to get Amy's attention through competition and courtship. 
        Vince attempts to impress Amy with skills as a cashier and his seventeen &quot;Employee of the Month&quot; awards, 
        while Zack attempts to use several methods of charm and comedy to win her affection. After realizing that 
        Amy is falling for Vince, Zack believes his only chance to get her is to win Super Club's next &quot;Employee of the Month&quot; award.
    </plot>    
    <copyright>
        <date>
            <year>2006</year>
        </date>        
        <companyname>Lions Gate Films Inc</companyname>
    </copyright>
    <other>
        <imdblink>http://www.imdb.com/title/tt0424993/</imdblink>
        <picture>dvd1.png</picture>
        <price></price>
    </other>
</dvd>

=== dmzoneill/www.feeditout.com-2008/samples/project2/dvd3.xml
<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE dvd SYSTEM "dvd.dtd">
<?xml-stylesheet href="reset.css" type="text/css"?>
<?xml-stylesheet href="book.css" type="text/css"?>
<dvd genre="thriller" runtime="153" viewing="18">    
    <title>The Terminal</title>    
    <presenter>
        <companyname>Dreamworks Pictures</companyname>
    </presenter>
    <production>
        <companyname>Parkes / McDaonald Films</companyname>
    </production>
    <released>
        <date>
            <year>2004</year>
        </date>
    </released>
    <producers>
        <person>
            <firstname>Steven</firstname>
            <surname>Spielberg</surname>
        </person>
    </producers>
    <coProducers>
        <person>
            <firstname>Sergio</firstname>
            <surname>Mimica-Gezzen</surname>
        </person>
    </coProducers>
    <musicProducers>
        <person>
            <firstname>John</firstname>
            <surname>Williams</surname>
        </person>
    </musicProducers>
    <costumeDesigners>
        <person>
            <firstname>Mary</firstname>
            <surname>Zophrite</surname>
        </person>
    </costumeDesigners>
    <directors>
        <person>
            <firstname>Steven</firstname>
            <surname>Spielberg</surname>
        </person>
    </directors>
    <actors>
        <person>
            <firstname>Tom</firstname>
            <surname>Hanks</surname>
        </person>
        <person>
            <firstname>Catherine</firstname>
            <surname>Zeta-Jones</surname>
        </person>
        <person>
            <firstname>Stanley</firstname>
            <surname>Tucci</surname>
        </person>
        <person>
            <firstname>Chi</firstname>
            <surname>McBride</surname>
        </person>
        <person>
            <firstname>Diego</firstname>
            <surname>Luna</surname>
        </person>       
    </actors>
    <plot>
        Viktor Navorski, a man from an Eastern European country arrives in New York. 
        However after he left his country war broke out. Suddenly Navorski is a man without a country - 
        or one that the U.S. cannot recognize, thus he is denied entrance to the U.S. However, 
        he also can't be deported so he is told by the Security Manager that he has to remain 
        in the airport until his status can be fixed. And also Navorski doesn't speak English very well, 
        so he cannot talk to or understand anyone. But he somehow adapts and sets up residence 
        in the airport, which makes the man who placed him there unhappy, as it seems he is in line 
        for a promotion but Navroski's presence might complicate that. So he tries to get Navorski to 
        leave but Navorski remains where he is. Navorski makes friends with some of the people who work 
        in the airport and is attracted to a flight attendant he runs into whenever she comes in. 
        Written by r.g.clark@gte.net
        
        An Eastern European visitor becomes a resident of a New York airport terminal when a war 
        breaks out and erases his country from the map, voiding his passport. He makes friends 
        with the airport staff and falls in love with a flight attendant. Written by BGW Claw
        
        Former Krakozhian Viktor Navorski is almost in New York City for the first time in his life. 
        "Former" and "almost"?: while Viktor is flying to JFK Airport, Krakozhia has been overthrown 
        as a country with no nation recognizing the new regime, therefore all government papers 
        such as passports, visas and currency issued by Krakozhia are also not recognized 
        internationally. With only these papers in hand when Viktor arrives at JFK, he is not allowed 
        entry into the United States. All air service in and out of Krakozhia has been suspended 
        and thus Viktor cannot even be sent back until Krakozhia's situation is resolved. 
        Frank Dixon, Director of Customs and Border Protection at JFK, allows Viktor to stay 
        in the international lounge until the problem is resolved. Dixon gives Viktor enough meal 
        vouchers to last for a day or two, with Dixon expecting Viktor to secretly escape the lounge 
        into the outside world. Viktor, however, wants to be as proper as possible and decides to 
        stay in the lounge. Viktor poses a problem for Dixon, as Viktor may be the black mark in 
        his promotion to head of the department. Their relationship becomes an antagonistic one, 
        where Dixon will now do whatever he can to prevent Viktor from ever entering the country 
        even if he ever did learn the heartbreaking reason for Viktor's visit. 
        As Viktor stays in the lounge, he only has limited resources on which to live and a 
        limited understanding of the English language. Viktor's encounters with lounge employees 
        is also initially antagonistic, but they all learn to live in harmony and friendship as 
        Viktor's stay increases. The one person Viktor would like to meet and know is United Airlines 
        flight attendant Amelia Warren, who is in transit through JFK every few weeks and who seems to 
        be dealing with her own personal demons.
    </plot>    
    <copyright>
        <date>
            <year>2004</year>
        </date>        
        <companyname>Dreamworks LLC</companyname>        
    </copyright>
    <other>
        <imdblink>http://www.imdb.com/title/tt0362227/</imdblink>
        <picture>dvd3.png</picture>
        <price></price>
    </other>
</dvd>

=== dmzoneill/www.feeditout.com-2008/samples/project2/dvd4.xml
<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE dvd SYSTEM "dvd.dtd">
<?xml-stylesheet href="reset.css" type="text/css"?>
<?xml-stylesheet href="book.css" type="text/css"?>
<dvd genre="comedy" runtime="168" viewing="12">    
    <title>Knocked Up</title>    
    <presenter>
        <companyname>Universal Pictures</companyname>
    </presenter>
    <production>
        <companyname>Apatow</companyname>
    </production>
    <released>
        <date>
            <year>2007</year>
        </date>
    </released>
    <producers>
        <person>
            <firstname>Jonathon</firstname>
            <surname>Karp</surname>
        </person>
    </producers>
    <coProducers>
        <person>
            <firstname>Calyton</firstname>
            <surname>Townsend</surname>
        </person>
    </coProducers>
    <musicProducers>
        <person>
            <firstname>Seth</firstname>
            <surname>Rogen</surname>
        </person>
    </musicProducers>
    <costumeDesigners>
        <person>
            <firstname>Eric</firstname>
            <surname>Edwards</surname>
        </person>
    </costumeDesigners>
    <directors>
        <person>
            <firstname>Jefferson</firstname>
            <surname>Sage</surname>
        </person>
    </directors>
    <actors>
        <person>
            <firstname>Seth</firstname>
            <surname>Rogen</surname>
        </person>
        <person>
            <firstname>Katherine</firstname>
            <surname>Heigl</surname>
        </person>
        <person>
            <firstname>Raul</firstname>
            <surname>Rudd</surname>
        </person>
        <person>
            <firstname>Leslie</firstname>
            <surname>Mann</surname>
        </person>       
    </actors>
    <plot>
        When Alison Scott is promoted in E! Television, she goes to a night-club to celebrate with her 
        older married sister Debbie. Alison meets the pothead reckless Ben Stone and while having a small 
        talk with Ben, Debbie's husband Pete calls her to tell that their daughter has chicken pots. 
        Debbie leaves the place but Allison stays with Ben, drinking and dancing along all night; 
        completely wasted, they end up having a one night stand. Ben does not use condom and eight 
        weeks later, Allison discovers that she is pregnant. She calls Ben and they decide to try to 
        stay together and have the baby. However, Ben needs to grow-up first to raise a family of his own. 
        Written by Claudio Carvalho, Rio de Janeiro, Brazil
        
        A one night stand turns into the unexpected for Ben, when Alison announces to him that she is 
        now pregnant with his child. Ben decides that the best thing to do is to get his life sorted 
        so he can care for Alison and his new child, which isn't an easy job for him.
    </plot>
    
    <copyright>
        <date>
            <year>2007</year>
        </date>
        <companyname>Universal Studios</companyname>        
    </copyright>
    <other>
        <imdblink>http://www.imdb.com/title/tt0478311/</imdblink>
        <picture>dvd4.png</picture>
        <price></price>
    </other>
</dvd>
