=== dmzoneill/www.feeditout.com-2008/samples/emmett/film.dtd
<!ELEMENT film (title, DVDCoverDetails, description, director, ((actor|actress),character?)+,award*)>
<!ENTITY R "Romantic"> 
<!ENTITY RC "Romantic comedy"> 
<!ENTITY RD "Romantic drama">
<!ELEMENT title (#PCDATA)>
<!ELEMENT DVDCoverDetails EMPTY>
<!ELEMENT description (#PCDATA)>
<!ELEMENT director (firstname,surname)>
<!ELEMENT actor (firstname,surname)>
<!ELEMENT actress (firstname,surname)>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT surname (#PCDATA)>
<!ELEMENT character (#PCDATA)>
<!ELEMENT award (#PCDATA)>
<!ATTLIST title 
boxSet  ( Yes | No ) "No"
genre CDATA #IMPLIED
id ID #REQUIRED
year CDATA #REQUIRED
time CDATA #IMPLIED
>
<!ATTLIST DVDCoverDetails 
width CDATA #IMPLIED
height CDATA #IMPLIED
DVDCoverDesign CDATA #IMPLIED
>

=== dmzoneill/www.feeditout.com-2008/samples/emmett/old files/Film1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE film SYSTEM "film.dtd">
<film boxSet = "No" genre="&R;"  id="DVD1" Year = "1995" time = "122">
    <title>Sabrina</title>
    <DVDCoverDetails width="10" height="10" DVDCoverDesign=".jpg"/>
    <director>
        <firstname>Sydney</firstname>
        <surname>Pollack</surname>
    </director>
    <actress>
        <firstname>Julia</firstname>
        <surname>Ormond</surname>
    </actress>
    <character>Sabrina</character>
    <actor>
        <firstname>Harrison</firstname>
        <surname>Ford</surname>
    </actor>
    <character>Linus</character>
    <actor>
        <firstname>Greg</firstname>
        <surname>Kinnear</surname>
    </actor>
    <character>Larrabee</character>
</film>

=== dmzoneill/www.feeditout.com-2008/samples/emmett/FilmTitanic.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE film SYSTEM "film.dtd">
<film>
    <title boxSet = "No" id="DVD2" year="2006" time = "194" >Titanic</title>
    <DVDCoverDetails width="10" height="10" DVDCoverDesign="Titanic.jpg"/>
    <description>Titanic is a 1997 American romantic drama film directed, written, co-produced and co-edited by James Cameron about the sinking of the RMS Titanic. It stars Leonardo DiCaprio as Jack Dawson and Kate Winslet as Rose DeWitt Bukater, two members of different social classes who fall in love aboard the ill-fated maiden voyage of the ship. The main characters and the central love story are fictional, but some characters (such as members of the ship's passengers and crew) are based on historical figures. Gloria Stuart plays the elderly Rose, who narrates the film in a modern day framing device.</description>
    <director>
        <firstname>James</firstname>
        <surname>Cameron</surname>
    </director>
    <actress>
        <firstname>Kate</firstname>
        <surname>Winslet</surname>
    </actress>
    <character>Rose DeWitt Bukater</character>
    <actress>
        <firstname>Gloria</firstname>
        <surname>Stuart</surname>
    </actress>
    <character>elderly Rose</character>
    <actor>
        <firstname>Leonardo</firstname>
        <surname>DiCaprio</surname>
    </actor>
    <character>Jack Dawson</character>
    <award>Oscar Best Picture</award>
    <award>Golden Globe Best Motion Picture</award>
</film>

=== dmzoneill/www.feeditout.com-2008/samples/emmett/FilmThe Holiday.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE film SYSTEM "film.dtd">
<film>
    <title boxSet="No" id="DVD2" year="2006" time="194">The Holiday</title>
    <DVDCoverDetails width="10" height="10" DVDCoverDesign="The Holiday.jpg"/>
    <description>The Holiday is a 2006 American romantic comedy film distributed by Columbia Pictures in the US and Universal Studios outside the US, starring Cameron Diaz, Kate Winslet, Jude Law, and Jack Black. The story involves two strangers who agree to swap homes temporarily</description>
    <director>
        <firstname>Nancy</firstname>
        <surname>Meyers</surname>
    </director>
    <actress>
        <firstname>Kate</firstname>
        <surname>Winslet</surname>
    </actress>
    <character>Iris</character>
    <actress>
        <firstname>Cameron</firstname>
        <surname>Diaz</surname>
    </actress>
    <character>Amanda</character>
    <actor>
        <firstname>Jude</firstname>
        <surname>Law</surname>
    </actor>
    <character>Graham Simpkins</character>
    <actor>
        <firstname>Jack</firstname>
        <surname>Black</surname>
    </actor>
    <character>Miles Dumont </character>
</film>

=== dmzoneill/www.feeditout.com-2008/samples/emmett/FilmSabrina.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE film SYSTEM "film.dtd">
<film>
    <title boxSet="No" id="DVD1" year="1995" time="122">Sabrina</title>
    <DVDCoverDetails width="10" height="10" DVDCoverDesign="Sabrina.jpg"/>    
    <description>Sabrina is a 1995 romantic comedy film adapted by Barbara Benedek and David Rayfiel, based on the 1954 screenplay of the same name, which in turn was based upon a play entitled Sabrina Fair.
        It was directed by Sydney Pollack, and stars Harrison Ford as Linus Larrabee, Julia Ormond as Sabrina and Greg Kinnear (in his first starring film role) as David Larrabee. It also features Angie Dickinson, Richard Crenna, Nancy Marchand, Lauren Holly, John Wood, Dana Ivey and French actress Fanny Ardant.
    </description>
    <director>
        <firstname>Sydney</firstname>
        <surname>Pollack</surname>
    </director>
    <actress>
        <firstname>Julia</firstname>
        <surname>Ormond</surname>
    </actress>
    <character>Sabrina</character>
    <actor>
        <firstname>Harrison</firstname>
        <surname>Ford</surname>
    </actor>
    <character>Linus Larrabee</character>
    <actor>
        <firstname>Greg</firstname>
        <surname>Kinnear</surname>
    </actor>
    <character>David Larrabee</character>
</film>

=== dmzoneill/www.feeditout.com-2008/samples/emmett/old files/Film2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE film SYSTEM "film.dtd">
<film boxSet = "No" genre="&RC;"  id="DVD2" Year = "2006" time = >
    <title>The Holiday</title>
    <DVDCoverDetails width="10" height="10" DVDCoverDesign=".jpg"/>
    <director>
        <firstname></firstname>
        <surname></surname>
    </director>
    <actress>
        <firstname>Kate</firstname>
        <surname>Winslet</surname>
    </actress>
    <character>Iris</character>
    <actress>
        <firstname>Cameron</firstname>
        <surname>Diaz</surname>
    </actress>
    <character>Amanda</character>
    <actor>
        <firstname>Jude</firstname>
        <surname>Law</surname>
    </actor>
    <character></character>
    <actor>
        <firstname>Jack</firstname>
        <surname>Black</surname>
    </actor>
    <character></character>
    <award></award>
    <award> </award>
</film>
